import Foundation
import SwiftData

@Model
final class Summary {
    var id: UUID
    var createdAt: Date
    var presetUsed: String
    var customPrompt: String?
    var modelUsed: String
    var content: String
    var isAutoGenerated: Bool

    var recording: Recording?

    init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        presetUsed: String,
        customPrompt: String? = nil,
        modelUsed: String,
        content: String,
        isAutoGenerated: Bool = false
    ) {
        self.id = id
        self.createdAt = createdAt
        self.presetUsed = presetUsed
        self.customPrompt = customPrompt
        self.modelUsed = modelUsed
        self.content = content
        self.isAutoGenerated = isAutoGenerated
    }
}
